#!/bin/sh

cd ${CLIENT_BASEDIR}/bin
sed "s|^  prefix=.*|  prefix=${CLIENT_BASEDIR}|1" log4shib-config > log4shib-config.tmp
mv log4shib-config.tmp log4shib-config
chmod 755 log4shib-config

cd ${CLIENT_BASEDIR}/lib/pkgconfig
sed "s|^prefix=.*|prefix=${CLIENT_BASEDIR}|1" log4shib.pc > log4shib.pc.tmp
mv log4shib.pc.tmp log4shib.pc
chmod 644 log4shib.pc

exit 0
