#!/bin/sh

cd ${CLIENT_BASEDIR}/lib/pkgconfig

sed "s|^prefix=.*|prefix=${CLIENT_BASEDIR}|1" libcrypto.pc > libcrypto.pc.tmp
mv libcrypto.pc.tmp libcrypto.pc
chmod 644 libcrypto.pc

sed "s|^prefix=.*|prefix=${CLIENT_BASEDIR}|1" libssl.pc > libssl.pc.tmp
mv libssl.pc.tmp libssl.pc
chmod 644 libssl.pc

sed "s|^prefix=.*|prefix=${CLIENT_BASEDIR}|1" openssl.pc > openssl.pc.tmp
mv openssl.pc.tmp openssl.pc
chmod 644 openssl.pc

exit 0
